<?php

declare(strict_types=1);

/**
 * Build script — concatenates all PlumePHP library files into a single
 * distributable dist/Plume.php.
 *
 * Usage:
 *   php scripts/build.php
 *   composer run build
 */

$rootDir = dirname(__DIR__);
$libDir  = $rootDir . '/library';
$distDir = $rootDir . '/dist';
$outFile = $distDir . '/Plume.php';

if (!is_dir($distDir)) {
    mkdir($distDir, 0755, true);
}

// ── Extract PLUME_VERSION from the master file ────────────────────────────────
$masterSrc = file_get_contents($libDir . '/PlumePHP.php');
if (!$masterSrc) {
    fwrite(STDERR, "ERROR: cannot read {$libDir}/PlumePHP.php\n");
    exit(1);
}
preg_match("/define\('PLUME_VERSION',\s*'([^']+)'\)/", $masterSrc, $vm);
$version = $vm[1] ?? 'unknown';

// ── Find require_once list in declaration order ───────────────────────────────
preg_match_all(
    "/^require_once __DIR__ \. '\/([^']+)';$/m",
    $masterSrc,
    $m
);
$relPaths = $m[1]; // e.g. 'Plume/Engine/Collection.php'

if (empty($relPaths)) {
    fwrite(STDERR, "ERROR: no require_once entries found in PlumePHP.php\n");
    exit(1);
}

// ── Strip <?php / declare header from a source string ────────────────────────
function stripHeader(string $src): string
{
    // Remove opening <?php tag (with optional BOM)
    $src = preg_replace('/^\xEF\xBB\xBF/', '', $src);          // BOM
    $src = preg_replace('/^<\?php\b[^\n]*\n/', '', $src);       // <?php line
    // Remove declare(strict_types=1); — may appear after a blank line
    $src = preg_replace('/^[ \t]*declare\s*\(\s*strict_types\s*=\s*1\s*\);\s*\n?/m', '', $src, 1);
    return ltrim($src, "\n");                                    // trim leading blank lines
}

// ── PSR-3 / PSR-11 stubs ─────────────────────────────────────────────────────
// Declared only when the real psr/* packages are absent so Plume.php works
// both standalone and inside a composer project that already has them.
$psrStubs = <<<'PHP_STUBS'
// ---------------------------------------------------------------------------
// PSR-3 stub (psr/log ^3). Skipped when the real package is already loaded.
// ---------------------------------------------------------------------------
namespace Psr\Log {
    if (!interface_exists(\Psr\Log\LoggerInterface::class, false)) {
        interface LoggerInterface
        {
            public function emergency(string|\Stringable $message, array $context = []): void;
            public function alert(string|\Stringable $message, array $context = []): void;
            public function critical(string|\Stringable $message, array $context = []): void;
            public function error(string|\Stringable $message, array $context = []): void;
            public function warning(string|\Stringable $message, array $context = []): void;
            public function notice(string|\Stringable $message, array $context = []): void;
            public function info(string|\Stringable $message, array $context = []): void;
            public function debug(string|\Stringable $message, array $context = []): void;
            public function log($level, string|\Stringable $message, array $context = []): void;
        }
    }
}

// ---------------------------------------------------------------------------
// PSR-11 stubs (psr/container ^2). Skipped when the real package is loaded.
// ---------------------------------------------------------------------------
namespace Psr\Container {
    if (!interface_exists(\Psr\Container\ContainerExceptionInterface::class, false)) {
        interface ContainerExceptionInterface extends \Throwable {}
    }
    if (!interface_exists(\Psr\Container\NotFoundExceptionInterface::class, false)) {
        interface NotFoundExceptionInterface extends \Psr\Container\ContainerExceptionInterface {}
    }
    if (!interface_exists(\Psr\Container\ContainerInterface::class, false)) {
        interface ContainerInterface
        {
            public function get(string $id): mixed;
            public function has(string $id): bool;
        }
    }
}

PHP_STUBS;

// ── Assemble output ───────────────────────────────────────────────────────────
$out  = "<?php\n\n";
$out .= "declare(strict_types=1);\n\n";
$out .= "/*\n";
$out .= " * Plume.php — PlumePHP {$version} single-file distribution.\n";
$out .= " * Built by scripts/build.php on " . date('Y-m-d') . ".\n";
$out .= " * Do not edit this file directly; edit the source files and re-run the build.\n";
$out .= " */\n\n";

// PSR stubs go in named-namespace blocks
$out .= $psrStubs . "\n";

// All framework classes live in the global namespace
$out .= "namespace {\n\n";

// Inline each required file (strip PHP header, keep body)
foreach ($relPaths as $rel) {
    $path = $libDir . '/' . $rel;
    if (!file_exists($path)) {
        fwrite(STDERR, "WARNING: missing {$path} — skipping\n");
        continue;
    }
    $body = stripHeader((string) file_get_contents($path));
    $out .= "// ── {$rel} ──\n";
    $out .= $body;
    $out .= "\n";
}

// Inline common.php (included at runtime via I() in Engine::boot, not via require_once).
// Must appear after PlumeHelper.php since it depends on that class.
$commonPath = $libDir . '/common.php';
if (file_exists($commonPath)) {
    $body = stripHeader((string) file_get_contents($commonPath));
    $out .= "// ── common.php ──\n";
    $out .= $body;
    $out .= "\n";
} else {
    fwrite(STDERR, "WARNING: {$commonPath} not found — common.php helpers will be missing from dist\n");
}

// Append master file: strip header + remove all require_once lines
$masterBody = stripHeader($masterSrc);
$masterBody = preg_replace(
    "/^require_once __DIR__ \. '\/[^']+';[ \t]*\n/m",
    '',
    $masterBody
);
$out .= "// ── PlumePHP.php ──\n";
$out .= $masterBody;

$out .= "\n} // namespace\n";

file_put_contents($outFile, $out);

$kb = number_format(strlen($out) / 1024, 1);
echo "Built dist/Plume.php  ({$kb} KB, PHP {$version})\n";
